volumes:
  lxnkup_local_postgres_data: {}
  lxnkup_local_postgres_data_backups: {}
  lxnkup_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: lxnkup_local_django
    container_name: lxnkup_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  frontend:
      build:
        context: ./frontend
        dockerfile: ../compose/local/next/Dockerfile
      image: lxnkup_local_nextjs
      container_name: lxnkup_local_nextjs
      volumes:
        - ./frontend:/app/frontend
        - /app/frontend/node_modules
      environment:
        - NODE_ENV=development
      ports:
        - "3000:3000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lxnkup_production_postgres
    container_name: lxnkup_local_postgres
    volumes:
      - lxnkup_local_postgres_data:/var/lib/postgresql/data
      - lxnkup_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: lxnkup_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: lxnkup_local_redis

    volumes:
      - lxnkup_local_redis_data:/data


  celeryworker:
    <<: *django
    image: lxnkup_local_celeryworker
    container_name: lxnkup_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: lxnkup_local_celerybeat
    container_name: lxnkup_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: lxnkup_local_flower
    container_name: lxnkup_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
