GET  http://localhost:8000/LxnkUp/api/Profiles/all

###
GET  http://localhost:8000/LxnkUp/api/Profiles/user/tester

###
PUT  http://localhost:8000/LxnkUp/api/Profiles/user/1
data: {"about": "new bio2"}
