# Generated by Django 5.1.7 on 2025-04-25 02:53

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='user')),
                ('location', models.TextField(blank=True, max_length=50, verbose_name='location')),
                ('is_visible', models.BooleanField(default=False)),
                ('dob', models.DateField(null=True)),
                ('dob_visible', models.BooleanField(default=False)),
                ('is_requesting_delete', models.BooleanField(default=False)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('TEEN', 'Teen'), ('SUSPENDED', 'Suspended')], db_index=True, default='REGULAR', help_text='\n        1. Regular profile\n        2. Teen profile\n        3. Suspended profile\n\n    ', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table_comment': 'lxnkup profile model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('blocked', models.ManyToManyField(related_name='blocked_profile', to='profiles.profile')),
                ('muted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted', to='profiles.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('vip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'db_table_comment': 'Interaction model for LxnkUp',
            },
        ),
    ]
