# Generated by Django 5.0.12 on 2025-03-04 02:25

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.photo')),
                ('timed', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
            bases=('photologue.photo',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='user')),
                ('timed', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
                ('dislikes', models.ManyToManyField(blank=True, related_name='video_dislike', to='profiles.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='video_like', to='profiles.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('view', models.ManyToManyField(blank=True, related_name='video_view', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.gallery')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_gallaries', to='profiles.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_video', to='medialog.video')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
            bases=('photologue.gallery',),
        ),
    ]
