# Generated by Django 5.0.12 on 2025-03-04 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('url', models.TextField(blank=True, db_index=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('VERIFIED', 'Verified'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('REDACTED', 'Redacted')], db_index=True, default='INITIATED', help_text='\n        1. Anyone can create a report. Does not mean it is valid.\n        2. Report is valid and further actions can be taken.\n        3. The report was verified but is no longer valid. The problem has been solved.\n        4. Verified and found the report has no basis. Fake/Invalid.\n        5. User is withdrawing the report.\n    ', max_length=10)),
                ('report_type', models.CharField(choices=[('HATE', 'Hate'), ('ABUSE and HARASSMENT', 'Abuse Harassment'), ('VIOLENT SPEECH', 'Violent Speech'), ('CHILD SAFETY', 'Child Safety'), ('PRIVACY', 'Privacy'), ('SPAM', 'Spam'), ('SUICIDE or SELF-HARM', 'Suicide'), ('SENSITIVE or DISTURBING MEDIA', 'Sensitive Media'), ('IMPERSONATION', 'Impersonation'), ('VIOLENT & HATEFUL GROUPS', 'Violent Group')], db_index=True, help_text='\n        1. Slurs, racist or sexist stereotypes, dehumanization, incitement of fear or\n        discrimination, hateful references, hateful symbols & logos.\n        2. Insults, unwanted sexual content & graphic objectification, unwanted NSFW &\n        graphic content,\n        violent event denial, targeted harassment, and inciting harassment.\n        3. Violent threats, wish of harm, glorification of violence, incitement of\n        violence, coded incitement of violence.\n        4. Child sexual exploitation, grooming, physical child abuse, underage user.\n        5. Sharing private information, threatening to share/expose private information,\n        sharing non-consensual intimate images, sharing images of me that\n         I don’t want on the platform.\n        6. Fake engagement, scams, fake accounts, malicious links.\n        7. Encouraging, promoting, providing instructions or\n        sharing strategies for self-harm.\n        8. Graphic content, gratuitous gore, adult nudity & sexual behavior, violent\n        sexual conduct, bestiality & necrophilia, media depicting a deceased individual.\n        9. Pretending to be someone else, including non-compliant parody/fan accounts.\n        10. Violent extremism and terrorism, hate groups & networks.\n    ', max_length=100)),
                ('report_investigation_comments', models.TextField(blank=True)),
                ('reported_object_id', models.PositiveIntegerField()),
                ('reported_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table_comment': 'Model for saving reports against profiles, posts etc',
                'ordering': ['-created_at'],
            },
        ),
    ]
