# Generated by Django 5.0.12 on 2025-03-04 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('blocked', models.ManyToManyField(related_name='blocked_profile', to='profiles.profile')),
                ('muted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted', to='profiles.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('vip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'db_table_comment': 'Interaction model for LxnkUp',
            },
        ),
    ]
