# Generated by Django 5.0.12 on 2025-03-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='reposts_allowed',
        ),
    ]
